version: '3.8'

services:
    suggestion_system_server:
        restart: on-failure
        build:
            context: ./docker
        volumes:
            - .:/var/www/html
            - ./docker/env-variables.ini:/usr/local/etc/php/conf.d/env-variables.ini
            - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
        environment:
            DB_HOST: suggestion_system_db
        ports:
            - 8000:8000
            - 5173:5173
        links:
            - suggestion_system_db
    suggestion_system_db:
        image: mariadb:latest
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./dbdata:/var/lib/mysql
        ports:
            - 3306:3306
    suggestion_system_phpma:
        image: phpmyadmin:latest
        restart: on-failure
        environment:
            PMA_HOST: suggestion_system_db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        links:
            - suggestion_system_db
        ports:
            - 8081:80
